name: "Build and test Lua project"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt install luarocks
      - uses: actions/checkout@v2
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "Build"
        run: |
           luarocks make
      - name: "Unit test"
        run: |
          tools/runtests
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out