name: "Build and test Lua project"

on: [push]
jobs:
  build:
    strategy:
       fail-fast: true
       matrix:
          lua_version: [5.1, 5.2, 5.3, 5.4]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lua-${{ matrix.lua_version }}
      cancel-in-progress: true
    name: "Build with Lua ${{ matrix.lua_version }}"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
           fetch-depth: 1
      - name: "Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get -y install lua${{ matrix.lua_version }} liblua${{ matrix.lua_version }} lua-any luarocks
      - name: Print versions
        run: |
          lua -v
          luarocks --version
          luarocks path
      - name: Install Lua dependencies
        run: |
          luarocks make --local
      - name: Run tests
        run: |
          luarocks test --local
      - name: Run static code analysis
        # Ignore:
        # - 212: unused argument self
        run: |
          "$HOME"/.luarocks/bin/luacheck src --codes --ignore 212
      - name: Create report
        run: |
          luacov -c .coverage_config.lua luacov.stats.out
          mkdir -p target/luacov-reports
          mv luacov.*.out target/luacov-reports/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov-report
          path: target/luacov-reports/*